README.md, app/assets/stylesheets/application.scss, build.sbt, run_acceptance_tests_dev.sh
Also adds shell script for acceptance tests.
=> PLATUI-638: Fix SASS asset path

build.sbt, conf/application.conf, project/plugins.sbt
I've added this to the assets, not the pages.  That matches tracking-consent.
=> Adding cache and gzip to assets

app/uk/gov/hmrc/accessibilitystatementfrontend/views/AccessibilityStatementTemplate.scala.html, conf/messages, conf/messages.cy, conf/services/example-partially-compliant.cy.yml, conf/services/example-partially-compliant.yml, conf/services/pay-what-you-owe-in-instalments.yml, test/unit/views/StatementPageSpec.scala
Making sure the Milestones are working as sentences.
=> Fixing the punctuation around milestones.

conf/services/agent.yml, conf/services/agents.yml, conf/services/cato.yml, conf/services/country-by-country-reporting.yml, conf/services/employment-intermediary-report.yml, conf/services/fhdds.yml
Combination of the following DLS-3215, DLS-3212, DLS-3211, DLS-3210
=> DLS-3215, DLS-3212, DLS-3211, DLS-3210

app/uk/gov/hmrc/accessibilitystatementfrontend/views/AccessibilityStatementTemplate.scala.html, test/unit/views/StatementPageSpec.scala
This should have been added before but was missed.
=> Added automated testing content 

conf/services/ask-for-copy-of-your-corporation-tax-utr.cy.yml, conf/services/ask-for-copy-of-your-corporation-tax-utr.yml
DDCE-1057
Added welsh content for Accessibility for CT-UTR.
=> DDCE-1057 Added ctutr welsh content

conf/services/ask-for-copy-of-your-corporation-tax-utr.cy.yml, conf/services/ask-for-copy-of-your-corporation-tax-utr.yml
DDCE-1057
Updated dates in the yml files, changed statementVisibility to public, changed contactFrontendServiceId and added few changes suggested by WLU team.
=> DDCE-1057 Updated dates and added WLU review changes

conf/services/payrolling-benefits-in-kind.cy.yml, conf/services/payrolling-benefits-in-kind.yml
Updated visibility to public and changed the dates to reflect this.
=> DDCE-1084: Updated visibility and dates

conf/services/relief-at-source.yml
Non-compliant statement created for RAS (relief at source)
=> [DP][DDCE-992]: Created noncompliant statement for RAS

conf/services/check-your-ers-files.cy.yml, conf/services/check-your-ers-files.yml
For the DDCE-1082 ticket this request involves the creation of the pages check-your-ers-files.cy.yml and check-your-ers-files.yml for implementing the accessibility statement for ERS.
=> DDCE-1082a: Creating check-your-ers-files

conf/services/hmrc-developer-hub.yml
- Set compliance to partial
- Set visibility to public
=> APIS-4888 - Added milestones dates to issues for hmrc-developer-hub FE

conf/services/relief-at-source.yml
Making RAS' accessibility statement visible in production
=> [DP][DDCE-992]: Updated RAS statement to public

conf/services/manage-pensions.yml, conf/services/pension-schemes.yml, conf/services/register-pension-administrator.yml
accessiblity statements for pension scheme services ( PODS ).
=> publish a11y statements

conf/services/oauth.yml
=> APIS-4899 - Added oauth front end accessibility statement

conf/services/manage-permissions-for-tax-software.yml
For the API Platform (AKA Revocation frontend)
=> APIS-4899 - Added statement for Manage permissions for tax software

conf/services/manage-permissions-for-tax-software.yml, conf/services/oauth.yml
for oauth and manage-permissions-for-tax-software
=> APIS-4899 - Update descriptions and set to public

conf/services/childcare-calculator.yml
=> DL-4230 - A11y statement functionality for Childcare calculator

conf/services/agent-epaye-registration.yml
=> DL-4232 - A11y statement functionality for OPRA

conf/services/payrolling-benefits-in-kind.cy.yml, conf/services/payrolling-benefits-in-kind.yml
Small change to update the incorrect contactFrontendServiceId from 'scp' to 'pbik'
=> contactFrontendServiceId change

conf/services/check-your-ers-files.cy.yml, conf/services/check-your-ers-files.yml
As a part of the ERS checks accessibility statements here I have updated the dates from 19th September to 22nd September in both the accessibility statements files for ERS checks i.e. check-your-ers-files.yml and check-your-ers-files-cy.yml.
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met? Yes
- Have you done a visual check of the changes? Yes
- Is there any still commented or unused code? Lingering printlns? No
- Have things been implemented in a complicated way? No
- Are the test still over the coverage threshold? No
- Does the compiler throw a lot of warnings? No
- Have methods and tests been named clearly? N/a
- Were there any changes in the config? Do changes need to be made in app-config-??? No
- Have you done a manual walkthrough? Yes
=> DDCE-1082:Implement accessibility statement for ERS-Checking-Frontend

conf/messages, project/AppDependencies.scala, test/unit/views/StatementPageSpec.scala
English only because I'll wait for a new Welsh translation from the design system.
=> Updated new tab link text

conf/services/register-pension-administrator.yml
=> serviceUrl changes

conf/services/hmrc-developer-hub.yml, conf/services/oauth.yml
Updated the fix dates for hmrc-developer-hub and oauth statements (to 31 March 2021)
=> APIS-4943 - Updated the fix dates for hmrc-developer-hub

conf/services/take-home-pay-calculator.cy.yml
=> [HMA-3744] Updated statement to reflect full compliance

conf/services/get-access-customs-declaration-service.cy.yml, conf/services/get-access-customs-declaration-service.yml, conf/services/get-eori-number.cy.yml, conf/services/get-eori-number.yml, conf/services/manage-email-cds.cy.yml, conf/services/manage-email-cds.yml
- Get an EORI number
- Get access to the CDS
- Manage your email for the CDS
=> Create new accessibility statements for 3 EORI related services

conf/services/check-tax-on-goods-you-bring-into-the-uk.yml
Adding Accessibilty statement for bc-passengers-frontend service
=> Adding Accessibilty statement for bc-passengers-frontend service

conf/services/customs-declare-exports.yml, conf/services/customs-movements.yml
Create an accessibility statement for the customs-movements
service. Also make some changes to the existing customs
declaration service accessibility statement.
=> CEDS-2942 Create & Ammend Statements for Exports Services

conf/services/pay.cy.yml, conf/services/pay.yml
Signed-off-by: olabode <15871275+Akure4Life@users.noreply.github.com>
=> Adding Pay frontend Accessibility statement

conf/services/pay-what-you-owe-in-instalments.cy.yml, conf/services/pay-what-you-owe-in-instalments.yml
Signed-off-by: olabode <15871275+Akure4Life@users.noreply.github.com>
=> Adding Self Assessment Payment Plan Accessibility statement

conf/services/submit-your-ers-annual-return.cy.yml, conf/services/submit-your-ers-annual-return.yml
Reverts hmrc/accessibility-statement-frontend#428
=> Revert "DDCE-1785: Updated ERS returns accessibility statement to be partiall…"

conf/services/check-tax-on-goods-you-bring-into-the-uk.cy.yml, conf/services/check-tax-on-goods-you-bring-into-the-uk.yml
Implement Updated Accessibility Statement
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???
=> PAS-1257:Implement Updated Accessibility Statement

conf/services/plastic-packaging-tax.yml
This was reviewed by our PPT content designer.
=> PPTP-338 Add PPT draft statement

conf/services/identity-verification.cy.yml, conf/services/identity-verification.yml, conf/services/lost-credentials.cy.yml
Adding the missing Welsh for LCFE compliant statement at the same time.
=> VER-648 [AL] Update IV statement following DAC assessment

conf/services/hmrc-android-app.yml, conf/services/hmrc-ios-app.yml
@mrolfe88, @chrisob55.  This will make your statements public.  I have updated the last updated date and the created date.  I haven't updated the testing date which looks like it might need updating.
You can change update this YAML and if you need permission to raise PRs you can request that on #team-plat-ui.   When this is merged and you're ready for a release just ask on #team-plat-ui.
=> Preparing for go-live of mobile app statements.

conf/services/check-tax-on-goods-you-bring-into-the-uk.cy.yml, conf/services/check-tax-on-goods-you-bring-into-the-uk.yml
Publish Compliant Accessibility Status
AT Link:N/A
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???
=> PAS-1397:Publish Compliant Accessibility Status

conf/services/direct-debit.cy.yml, conf/services/direct-debit.yml, conf/services/pay-what-you-owe-in-instalments.cy.yml, conf/services/pay-what-you-owe-in-instalments.yml, conf/services/pay.cy.yml, conf/services/pay.yml, conf/services/vat-repayment-tracker.cy.yml, conf/services/vat-repayment-tracker.yml
Reverts hmrc/accessibility-statement-frontend#484
=> Revert "[CC][OPS-6213]Removed accessibility statements for payments"

conf/services/class2-national-insurance.cy.yml, conf/services/class2-national-insurance.yml
This service is now fully compliant and I have updated both the English and Welsh versions to reflect this.
=> Updating c2ni National insurance class 2 accessibility statement

conf/services/self-employed-income-support-scheme.cy.yml, conf/services/self-employed-income-support-scheme.yml
SEISS-1551: Added yml file for seiss
=> SEISS-1551: Added yml file for seiss

conf/services/pension-practitioners.yml
PODS-5790 : Update Accessibility Statement of Pension scheme Practitioner
=> PODS-5790 : Update Accessibility Statement of Pension scheme Practitioner

conf/services/customs-financials.cy.yml, conf/services/customs-financials.yml
This PR is to update the accessibility statement for CDS financials
=> update accessibility statement for cds financials

conf/services/income-tax-submission.cy.yml, conf/services/income-tax-submission.yml
Change all `/income-through-software/return/` strings to `/update-and-submit-income-tax-return/`
[SASS-1685](https://jira.tools.tax.service.gov.uk/browse/SASS-1685)
=> SASS-1685: Update accessibility statement page URLs

conf/services/get-eori-number.cy.yml, conf/services/get-eori-number.yml
Updating `get-eori-number` accessibility statement dates.
=> GYE-2684 - Get EORI number accessibility update

conf/services/tax-credits-renewals.cy.yml, conf/services/tax-credits-renewals.yml
Signed-off-by: Phil Sherry <272769+philsherry@users.noreply.github.com>
=> Based on work of DDCNL-4483.

conf/services/marriage-allowance.cy.yml, conf/services/marriage-allowance.yml, conf/services/tamc-frontend.cy.yml, conf/services/tamc-frontend.yml
Signed-off-by: Phil Sherry <272769+philsherry@users.noreply.github.com>
=> Aligning TAMC's situation

conf/services/income-tax-view-change.cy.yml
Corrected dates in the 'milestone' section of the statement as the source was giving incorrect month/day.
=> MISUV-2705-2

conf/services/digital-engagement-platform-frontend.yml
Update required to Accessibility statement
=> [DEP-2437][PR]:Update required to Accessibility statement

conf/services/income-tax-sign-up.cy.yml, conf/services/income-tax-sign-up.yml
=> ITSASU-845: Accessibility statement text fix

conf/services/sdlt.yml
Statement update and all unit tests pass.
=> Update SDLT accessibility statement inline with most recent DAC report

conf/services/check-your-ers-files.cy.yml, conf/services/check-your-ers-files.yml
We need to implement a fully compliant accessibility statement for ERS Checking, so that users know the service has no accessibility issues. The statement lives in the accessibility statement microservice and we need to update the following lines on the YAML:
complianceStatus: full
serviceLastTestedDate: 11/03/2022
statementLastUpdatedDate: <Date of deployment>
https://github.com/hmrc/accessibility-statement-frontend/blob/main/conf/services/check-your-ers-files.cy.yml
https://github.com/hmrc/accessibility-statement-frontend/blob/main/conf/services/check-your-ers-files.yml
Example of full compliant statement - https://github.com/hmrc/accessibility-statement-frontend/blob/main/conf/services/lifetime-isa.yml
A/C's
=> DDCE-2900 - ERS Checking fully compliant accessibility statement

conf/services/employers-pay-as-you-earn.cy.yml, conf/services/employers-pay-as-you-earn.yml
- includes Welsh translation
For Live Services story DL-7199
=> DL-7199 Update EPAYE statement inline with most recent DAC report

conf/services/vat-flat-rate-calculator.yml
Live service accessibility statement update story DL-7204
=> DL-7204 Update VAT FRS statement inline with most recent audit

conf/services/capital-gains-tax-calculator-non-resident.cy.yml, conf/services/capital-gains-tax-calculator-non-resident.yml
=> DL-7203-CGT-non-resident Update CGT non resident inline with latest DAC

conf/services/capital-gains-tax-calculator-resident-shares.cy.yml, conf/services/capital-gains-tax-calculator-resident-shares.yml
=> DL-7202-CGT-resident-shares Update CGT resident shares statement inline with latest DAC

conf/services/childcare-calculator.cy.yml, conf/services/childcare-calculator.yml
=> DL-7201-CCC Update childcare calculator inline with most recent DAC report

conf/services/capital-gains-tax-calculator-resident-properties.cy.yml, conf/services/capital-gains-tax-calculator-resident-properties.yml
This update includes Welsh translation.
=> DL-7200 Updating CGT resident properties statement inline with latest DAC report

project/AppDependencies.scala
- bump play-frontend-hmrc versions to latest
=> NOJIRA-update-dependencies

conf/services/tax-credits-calculator.cy.yml, conf/services/tax-credits-calculator.yml
=> DL-7206 Updating TCC statement inline with latest DAC

conf/services/pensions-lifetime-allowance.cy.yml, conf/services/pensions-lifetime-allowance.yml
=> DL-7205-PLA Updating PLA statement inline with latest DAC

app/uk/gov/hmrc/accessibilitystatementfrontend/models/Enum.scala, app/uk/gov/hmrc/accessibilitystatementfrontend/models/package.scala, test/unit/parsers/AccessibilityStatementYamlParserSpec.scala
Off the back of work done in [PLATUI-1659](https://jira.tools.tax.service.gov.uk/browse/PLATUI-1659) I noticed a few compiler warnings that could be fixed easily.
=> Fixed compiler warnings

conf/services/digital-forms-service.cy.yml, conf/services/digital-forms-service.yml
=> DL-7212 Update DFS statement inline with latest DAC

conf/services/inheritance-tax.cy.yml, conf/services/inheritance-tax.yml
Welsh translation included.
Also, this service is due to be decommisioned on 1 January 2023 and there is no budget to address the fixes listed because of this. Hence the update date.
=> DL-6822-IHT Update IHT statement inline with latest DAC

conf/services/income-record-viewer.cy.yml, conf/services/income-record-viewer.yml
# DDCE-2995 - IRV accessibility statement
English
Welsh:
=> DDCE-2995 - IRV accessibility statement

conf/services/digital-engagement-platform-frontend.yml
[DEP-3150][PR]:Implement DAC issue content on accessibility statement page
=> [DEP-3150][PR]:Implement DAC issue content on accessibility statement page

conf/services/employee-expenses.cy.yml, conf/services/employee-expenses.yml
=> DL-7210 updating EE inline with latest DAC

conf/services/check-transit-guarantee-balance.yml
=> CTCP-573: Guarantee balance a11y statement updated.

conf/services/advance-tariff-application.cy.yml, conf/services/advance-tariff-application.yml, conf/services/charities.yml, conf/services/check-tax-on-goods-you-bring-into-the-uk.cy.yml, conf/services/check-tax-on-goods-you-bring-into-the-uk.yml, conf/services/manage-tariff-classifications.yml, conf/services/payrolling-benefits-in-kind.cy.yml, conf/services/payrolling-benefits-in-kind.yml
Metadata updates for Team Alpha Services
=> DDCE-3175 : metadata updates for Team Alpha Services

conf/services/income-record-viewer.cy.yml, conf/services/income-record-viewer.yml
Please do not merge yet as we are awaiting signoff from the Welsh translation team
=> DDCE-3243 : Update a11y statement following latest retest

conf/services/capital-gains-tax-calculator-non-resident.cy.yml, conf/services/capital-gains-tax-calculator-non-resident.yml, conf/services/capital-gains-tax-calculator-resident-properties.cy.yml, conf/services/capital-gains-tax-calculator-resident-properties.yml, conf/services/capital-gains-tax-calculator-resident-shares.cy.yml, conf/services/capital-gains-tax-calculator-resident-shares.yml
CGT is a 3 part service of, which is just 1 of many services for DDCT Live Services and is currently in the process of being upgraded along with many other services. This  date changes allows for a more realistic timeline before getting the service retested after the current ui upgrade is complete.
=> Updating dates for CGT to provide a more realistic resolution deadline.

conf/services/plastic-packaging-tax.cy.yml
Updating with latest Welsh content.
Source: https://docs.google.com/spreadsheets/d/1D8uTvNVY3tTm82K0HdX1E6FszdW4pqhX/edit#gid=408523485
=> PPT - Adding Welsh content updates

conf/services/payrolling-benefits-in-kind.cy.yml, conf/services/payrolling-benefits-in-kind.yml
Statement update for 2022-09-29
=> DDCE-3459: PBIK Accessibility statement update

conf/services/alcohol-wholesale-scheme.yml, conf/services/ated.yml, conf/services/calculate-stamp-duty-land-tax.yml, conf/services/capital-gains-tax-calculator-non-resident.cy.yml, conf/services/capital-gains-tax-calculator-non-resident.yml, conf/services/capital-gains-tax-calculator-resident-properties.cy.yml, conf/services/capital-gains-tax-calculator-resident-properties.yml, conf/services/capital-gains-tax-calculator-resident-shares.cy.yml, conf/services/capital-gains-tax-calculator-resident-shares.yml, conf/services/safety-and-security-subscription.cy.yml, conf/services/safety-and-security-subscription.yml, conf/services/sdlt.yml
Bulk date updates for Telford LS
=> Bulk date updates - Telford lS updates dl-9452

conf/services/payrolling-benefits-in-kind.cy.yml, conf/services/payrolling-benefits-in-kind.yml
Statement updated to be fully compliant.
=> DDCE-3640: PBIK Accessibility statement to fully compliant

conf/services/digital-engagement-platform-frontend.yml
Updated fixed by dates for Digital Engagement Platform Frontend
=> DEP-4649 update DEP statement

conf/services/check-an-hgv-is-ready-to-cross-the-border.yml
Service is now a series of web pages. Archiving as statement no longer required.
=> Archiving check-an-hgv-is-ready-to-cross-the-border.yml

conf/services/contact.yml
Archiving service that is no longer publicly available.
=> Archived Contact.yml

conf/services/safety-and-security-subscription.yml
Archiving service that is no longer publicly available.
=> Archived safety-and-security-subscription.yml

conf/services/tamc-frontend.yml
Archiving duplicate service statement.
=> Archived tamc-frontend.yml

conf/services/income-tax.yml
Archiving duplicate service statement.
=> Archived income-tax.yml

conf/services/cti.yml
Archiving duplicate service statement.
=> Archived cti.yml

conf/services/child-benefit.cy.yml
Some more requested updates from the WLU now that they can see out statement in full content
=> ChB Updates requested by the WLU.

conf/services/api-hub.yml
https://jira.tools.tax.service.gov.uk/browse/HIPP-363
=> HIPP-363: Add the accessibility statement to the API Hub

conf/services/soft-drinks-industry-levy-registration-frontend.yml
=> DLS-8847 added accessibility statement for sdil registration

conf/services/ated-subscription.yml
- Updated accessibility statement.
- Ran ated-subscription locally http://localhost:12346/accessibility-statement/ated-subscription.
- Ran unit tests and integration tests, both passed.
=> DL-11674 updated accessibility statement ated subscription

conf/services/agent-client-mandate.yml
- Updated accessibility statement
- Ran local test http://localhost:12346/accessibility-statement/agent-client-mandate
- Ran Unit tests and Integration tests
=> DL-11675 updated accessibility statement for ACM

conf/services/advance-valuation-ruling.yml
Updated accessibility statement 'target fix date' for issues found in the Advance Valuation Rulings service.
=> ARSSTB-349 Update accessibility statement 'target fix date' for issues

conf/services/awrs-lookup.cy.yml, conf/services/awrs-lookup.yml
Update statement for awrs lookup to partial
Update English and Welsh
=> DL-11590 update statement AWRS Lookup

app/uk/gov/hmrc/accessibilitystatementfrontend/tasks/StatementReportTask.scala, conf/services/income-tax-software-choices.yml, test/helpers/TestAccessibilityStatementRepo.scala, test/helpers/TestAccessibilityStatements.scala, test/it/StatementPageISpec.scala, test/unit/controllers/StatementControllerSpec.scala, test/unit/tasks/ReportSpec.scala
This PR ensures that newline characters are removed from all rows and tests are updated around this.
=> PLATUI-2594 fix report line breaks

conf/services/soft-drinks-industry-levy-registration.yml, conf/services/soft-drinks-industry-levy-returns.yml
I was able to view both locally per instructions, and unit tests and ITs pass.
=> Dls 9031 sdil reg and returns

conf/services/emcs-tfe-explain-delay-frontend.yml, conf/services/emcs-tfe-explain-shortage-excess-frontend.yml, conf/services/emcs-tfe-report-a-receipt-frontend.yml
Accessibility statements for the following 3 frontend's
- emcs-tfe-explain-delay-frontend
- emcs-tfe-explain-shortage-excess-frontend
- emcs-tfe-report-a-receipt-frontend
=> ETFE-1959 EMCS TFE

conf/services/hmrc-developer-hub.yml
Updated with latest DAC report findings
=> APIS-6603: API Platform statement update

conf/services/residence-nil-rate-band-calculator.cy.yml, conf/services/residence-nil-rate-band-calculator.yml
Oops I misspelled branch name RBRB doh!
=> RNRB is now compliant, updating both English and Welsh statements

conf/services/agent.cy.yml, conf/services/agent.yml, conf/services/capital-gains-tax-calculator-non-resident.cy.yml, conf/services/capital-gains-tax-calculator-non-resident.yml, conf/services/capital-gains-tax-calculator-resident-properties.cy.yml, conf/services/capital-gains-tax-calculator-resident-properties.yml, conf/services/capital-gains-tax-calculator-resident-shares.cy.yml, conf/services/capital-gains-tax-calculator-resident-shares.yml, conf/services/charities.yml, conf/services/ers.yml, conf/services/statutory-sick-pay-checklist.yml
updated the ddc and liveOrClassic fields.
Also changed the statement visibility to draft as we were informed by Dave Cross on 1/11/23 that this service has been shuttered and it will be decommissioned after the covid enquiry.
=> Update several yml files

conf/services/country-by-country-reporting.yml
Updating compliance statement for CBC service according to https://jira.tools.tax.service.gov.uk/browse/DLS-9492
=> DLS-9492 Update CBC compliance statement

conf/services/attachments.yml
(and set the statementVisibility to archived)
This reverts commit 988dd885ab624505d96d1fdc8527ce1316612c5b.
Requested by DIAS in our catch-up call earlier
=> Revert "delete attachments as service is decommissioned"

.gitignore, conf/messages, conf/messages.cy, project/plugins.sbt, test/acceptance/specs/StatementPageSpec.scala, test/unit/views/StatementPageSpec.scala
- Updates the hardcoded deadline for non-compliant services from 1 December 2023 to 30 June 2024
- Update unit tests to reflect changes
=> PLATUI-2788 update hardcoded deadline

conf/services/marginal-relief-calculator.cy.yml, conf/services/marginal-relief-calculator.yml
Updates for ticekt
https://jira.tools.tax.service.gov.uk/browse/DLS-9938
=> DLS-9938 [MRC] Update Accessibility Statement

conf/services/employment-intermediary-report.cy.yml, conf/services/employment-intermediary-report.yml
Updates for ticket:
https://jira.tools.tax.service.gov.uk/browse/DLS-9939
=> DLS-9939 [EI] Update Accessibility Statement

conf/services/api-hub.yml
Updating various estimated completion dates for API Hub issues
=> HIPP-1004 updating api-hub.yml

conf/services/paye.yml
Updated the PAYE accessibility conf
=> [CS-4330] PAYE-EXB: Accessibility Statement update

conf/services/employee-working-from-home-expenses.yml
From noncompliant to partially with details and milestones included
=> Updating EE WFH accessibility statement

conf/services/attachments.yml, conf/services/check-an-hgv-is-ready-to-cross-the-border.cy.yml, conf/services/coronavirus-job-retention-scheme.yml, conf/services/get-access-customs-declaration-service.cy.yml, conf/services/get-eori-number.cy.yml, conf/services/inheritance-tax.cy.yml, conf/services/inheritance-tax.yml, conf/services/repayments.cy.yml, conf/services/safety-and-security-subscription.cy.yml, conf/services/tamc-frontend.cy.yml, conf/services/vat-deferral-new-payment-scheme.cy.yml
Archiving the Welsh statement as only the English one was archived before. Note that even though this is meant to be a Welsh statement, it's written in English for some reason so I've put the word 'Archived' in English.
=> Archive statements

conf/services/get-access-customs-declaration-service.cy.yml, conf/services/get-eori-number.cy.yml
Removed the word 'Archived' from the statement. Please DO NOT go back in and add it again, it isn't meant to be on the Welsh statement.
=> Remove the word 'archived' where it has been put incorrectly.

conf/services/digital-engagement-platform-frontend.yml
Updated the DEP accessibility statement date.
=> DEP-6421 Updated the accessibility statement

conf/services/disclose-cross-border-arrangements.yml, conf/services/enter-cross-border-arrangements.yml, conf/services/register-for-cross-border-arrangements.yml
these should be marked archived but not deleted
they won't display in production when archived
=> PLATUI-3062: Revert deletion of some statements for DIAS

conf/services/integration-hub.yml
https://jira.tools.tax.service.gov.uk/browse/HIPP-1398
Rebranding of The API Hub to The Integration Hub
=> HIPP-1398: Update URLs

project/AppDependencies.scala
- Bump play-frontend-hmrc to latest version (10.6.0)
=> PLATUI-3172 bump play-frontend-hmrc version

project/AppDependencies.scala
- Bump `play-frontend-hmrc` version to `latest` (`10.12.0`)
=> PLATUI-3265 bump play-frontend-hmrc to latest

conf/services/marriage-allowance.cy.yml, conf/services/marriage-allowance.yml
Integration tests passed locally
=> Update English/Welsh accessibility statements for Marriage Allowance

conf/services/emcs-tfe-alert-rejection-frontend.yml, conf/services/emcs-tfe-cancel-movement-frontend.yml, conf/services/emcs-tfe-change-destination-frontend.yml, conf/services/emcs-tfe-create-movement-frontend.yml, conf/services/emcs-tfe-explain-delay-frontend.yml, conf/services/emcs-tfe-explain-shortage-excess-frontend.yml, conf/services/emcs-tfe-frontend.yml, conf/services/emcs-tfe-report-a-receipt-frontend.yml
Added 'Archived' wording to serviceName to reflect archived state of statement in case users navigate directly to statement.
=> Wdomanskihmrc patch 3

conf/services/agent.cy.yml, conf/services/agent.yml
For both english and welsh versions
=> DL-14837: Update from WCAG 2.1 to WCAG 2.2 in Agent

conf/services/pillar2-frontend.yml
Update accessibility statement
=> [PIL-1385-pillar2] Update pillar2-frontend accessibility statement

conf/services/pillar2-frontend.yml
=> [PIL-1385-pillar2-update] Remove negative contraction

conf/services/awrs-lookup.cy.yml, conf/services/awrs-lookup.yml
DL-14836, Upgraded wcagVersion for AWRS to 2.2
=> DL-14836, Upgraded wcagVersion for AWRS

conf/services/child-benefit-make-a-claim.cy.yml, conf/services/child-benefit-make-a-claim.yml
New branch as original commits were unsigned
=> added new claim child benefit service

conf/services/pillar2-frontend.yml
Update pillar2 after our latest accessibility test
=> [PIL-1430-update-pillar2] Update pillar2 accessibility statement

conf/services/claim-tax-relief-expenses.cy.yml, conf/services/claim-tax-relief-expenses.yml, conf/services/employee-working-from-home-expenses.yml, conf/services/professional-subscriptions.cy.yml, conf/services/professional-subscriptions.yml, conf/services/tax-credits-calculator.cy.yml, conf/services/tax-credits-calculator.yml
Archiving the statement as Dave Cross (live services Telford) informed DIAS that this service has been decommissioned.
=> Archive live services statements

conf/services/gvms-service-availability.cy.yml, conf/services/gvms-service-availability.yml
Amends the gvms-service-availability.yml and cy counterpart with new wcagVersion.
=> RORO-5590: GVMS Service Availability - Amend accessibility statement version.

conf/services/agent-client-mandate.yml, conf/services/alcohol-wholesale-scheme.yml, conf/services/ated-subscription.yml, conf/services/ated.yml, conf/services/calculate-stamp-duty-land-tax.yml, conf/services/claim-tax-relief-expenses.cy.yml, conf/services/claim-tax-relief-expenses.yml, conf/services/employee-expenses.cy.yml, conf/services/employee-expenses.yml, conf/services/employee-working-from-home-expenses.yml, conf/services/employers-pay-as-you-earn.cy.yml, conf/services/employers-pay-as-you-earn.yml, conf/services/inheritance-tax.cy.yml, conf/services/inheritance-tax.yml, conf/services/pensions-lifetime-allowance.cy.yml, conf/services/pensions-lifetime-allowance.yml, conf/services/professional-subscriptions.cy.yml, conf/services/professional-subscriptions.yml, conf/services/safety-and-security-subscription.cy.yml, conf/services/safety-and-security-subscription.yml
DL-15450, DL-15490: Updated telford live service statement
=> DL-15450, DL-15490: Updated telford live service statements

conf/services/alcohol-duty-returns-frontend.yml
[ADR-1739](https://jira.tools.tax.service.gov.uk/browse/ADR-1739) DEV QA : Add Fully Compliant Accessibility Statement to ADR service
Adding an accessibility statement for the ADR service in preparation for public beta on the first of March
=> ADR-1739 accessibility statement alcohol duty returns frontend

conf/services/agent-client-mandate.yml, conf/services/alcohol-wholesale-scheme.yml, conf/services/ated-subscription.yml, conf/services/ated.yml, conf/services/calculate-stamp-duty-land-tax.yml, conf/services/employee-expenses.cy.yml, conf/services/employee-expenses.yml, conf/services/interactive-guidance.cy.yml, conf/services/interactive-guidance.yml, conf/services/pensions-lifetime-allowance.cy.yml, conf/services/pensions-lifetime-allowance.yml
The last updated date is incorrect on most of Telford live service statements so I've updated it.
=> Live service statement updates

conf/services/claim-tax-relief-expenses.yml
DL-16104: removed archive status for EE
=> DL-16104: removed archive status for EE

conf/services/employers-pay-as-you-earn.cy.yml, conf/services/employers-pay-as-you-earn.yml
DL-15695:updated epaye status to complaint
=> DL-15695:updated epaye status to complaint

conf/services/alcohol-duty-returns-frontend.cy.yml
=> ADR-2187: Accessibility statement in Welsh

build.sbt, project/AppDependencies.scala
- Bump play-frontend-hmrc to latest
=> PLATUI-3936 bump play-frontend-hmrc dependency

conf/services/pillar2.yml
Implementing [PIL-2228](https://jira.tools.tax.service.gov.uk/browse/PIL-2228):
- Changes the path from the microservice name to the service name
- Updates the statement following passing accessibility audit on 27th Aug
=> Pillar 2 - Update accessibility statement
